'use client';
import { useState } from 'react';

const slides = [
  {
    title: "Pregnancy and Kidney",
    subtitle: "A Comprehensive Medical Review",
    content: [
      "References:",
      "• Davidson's Principles and Practice of Medicine",
      "• Kumar and Clark's Clinical Medicine",
      "• Harrison's Principles of Internal Medicine"
    ]
  },
  {
    title: "Normal Renal Physiology in Pregnancy",
    subtitle: "Anatomical Changes",
    content: [
      "Kidney Size and Structure:",
      "• Kidney length increases by 1-1.5 cm",
      "• Renal volume increases by 30%",
      "• Collecting system dilation (physiologic hydronephrosis)",
      "• More prominent on right side (90%) than left (67%)",
      "",
      "Mechanism:",
      "• Hormonal effects (progesterone)",
      "• Mechanical compression by gravid uterus",
      "• Dextrorotation of uterus affects right ureter more",
      "• Smooth muscle relaxation",
      "• Ureteral dilation can persist 12-16 weeks postpartum"
    ]
  },
  {
    title: "Renal Hemodynamics in Pregnancy",
    subtitle: "Blood Flow Changes",
    content: [
      "Renal Blood Flow (RBF):",
      "• Increases by 50-80% by mid-pregnancy",
      "• Peaks at 1200 mL/min (non-pregnant: 800 mL/min)",
      "• Begins in first trimester, peaks at 16-24 weeks",
      "",
      "Glomerular Filtration Rate (GFR):",
      "• Increases by 40-50% above baseline",
      "• Rises from 110 mL/min/1.73m² to 150-170 mL/min/1.73m²",
      "• Elevation starts by 6 weeks gestation",
      "• Maintained throughout pregnancy",
      "• Returns to baseline by 6-12 weeks postpartum"
    ]
  },
  {
    title: "Mechanisms of Increased GFR",
    subtitle: "Physiological Basis",
    content: [
      "Primary Mechanisms:",
      "• Increased cardiac output (30-50%)",
      "• Decreased systemic vascular resistance",
      "• Decreased renal vascular resistance",
      "• Preferential afferent arteriolar dilation",
      "",
      "Hormonal Factors:",
      "• Increased nitric oxide production",
      "• Relaxin effects on renal vasculature",
      "• Decreased vasopressin threshold",
      "• Altered prostaglandin synthesis",
      "• Reduced sensitivity to angiotensin II"
    ]
  },
  {
    title: "Changes in Serum Creatinine",
    subtitle: "Normal Pregnancy Values",
    content: [
      "Serum Creatinine:",
      "• Non-pregnant: 0.6-1.1 mg/dL (53-97 μmol/L)",
      "• Pregnancy: 0.4-0.8 mg/dL (35-71 μmol/L)",
      "• Mean decrease of 0.4 mg/dL",
      "",
      "Blood Urea Nitrogen (BUN):",
      "• Non-pregnant: 10-20 mg/dL",
      "• Pregnancy: 5-12 mg/dL",
      "",
      "Clinical Implications:",
      "• Creatinine >0.9 mg/dL in pregnancy may indicate renal dysfunction",
      "• Standard reference ranges not applicable",
      "• Need pregnancy-specific cutoffs for diagnosis"
    ]
  },
  {
    title: "Uric Acid Handling in Pregnancy",
    subtitle: "Filtration and Reabsorption",
    content: [
      "Serum Uric Acid Levels:",
      "• First trimester: 2.0-4.2 mg/dL",
      "• Second trimester: 2.4-4.9 mg/dL",
      "• Third trimester: 3.1-6.3 mg/dL",
      "",
      "Mechanisms:",
      "• Increased GFR causes initial decrease",
      "• Enhanced proximal tubular reabsorption later",
      "• Volume expansion effect",
      "• Estrogen influences urate transport",
      "",
      "Clinical Significance:",
      "• Hyperuricemia marker in preeclampsia",
      "• Level >5.5 mg/dL in late pregnancy abnormal"
    ]
  },
  {
    title: "Proteinuria in Normal Pregnancy",
    subtitle: "Physiological Changes",
    content: [
      "Normal Values:",
      "• Non-pregnant: <150 mg/24 hours",
      "• Pregnancy: <300 mg/24 hours",
      "• Protein:creatinine ratio <0.3",
      "",
      "Mechanism of Increased Excretion:",
      "• Increased glomerular permeability",
      "• Increased filtered load",
      "• Relative tubular reabsorptive capacity unchanged",
      "",
      "Clinical Distinction:",
      "• >300 mg/24h = pathological proteinuria",
      "• Requires investigation",
      "• May indicate preeclampsia or renal disease"
    ]
  },
  {
    title: "Glycosuria in Pregnancy",
    subtitle: "Tubular Function Changes",
    content: [
      "Glucose Handling:",
      "• Decreased tubular reabsorptive capacity for glucose",
      "• Present in 50% of normal pregnancies",
      "• Not directly correlated with blood glucose",
      "• Glucose threshold lowered",
      "",
      "Mechanism:",
      "• Increased GFR increases filtered glucose load",
      "• Tubular transport maximum (Tm) relatively decreased",
      "• Hormonal effects on glucose transporters",
      "",
      "Clinical Implications:",
      "• Common and usually benign",
      "• Does not indicate diabetes mellitus",
      "• Should still screen for gestational diabetes",
      "• Persistent glycosuria requires OGTT"
    ]
  },
  {
    title: "Amino Acids and Vitamins",
    subtitle: "Increased Urinary Losses",
    content: [
      "Amino Acid Excretion:",
      "• Increased excretion of all amino acids",
      "• Particularly histidine, serine, threonine, alanine, glycine",
      "• 2-4 fold increase in aminoaciduria",
      "",
      "Water-Soluble Vitamins:",
      "• Increased urinary losses of folate",
      "• Vitamin B6 and B12 excretion increased",
      "",
      "Clinical Management:",
      "• Routine folate supplementation essential",
      "• 400-800 μg folic acid daily",
      "• Prevents neural tube defects",
      "• Multivitamin supplementation recommended"
    ]
  },
  {
    title: "Acid-Base Balance",
    subtitle: "Respiratory Compensation",
    content: [
      "Physiological Changes:",
      "• Chronic respiratory alkalosis",
      "• pCO₂ decreases from 40 to 30 mmHg",
      "• HCO₃⁻ decreases from 24 to 18-20 mEq/L",
      "• pH remains 7.40-7.45 (compensated)",
      "",
      "Mechanism:",
      "• Progesterone-stimulated hyperventilation",
      "• Increased respiratory center sensitivity to CO₂",
      "• Renal compensation via bicarbonate excretion",
      "",
      "Clinical Significance:",
      "• Lower bicarbonate is normal in pregnancy",
      "• Reduced buffering capacity",
      "• Less tolerance for metabolic acidosis"
    ]
  },
  {
    title: "Electrolyte Changes",
    subtitle: "Sodium and Water Balance",
    content: [
      "Sodium Handling:",
      "• Total body sodium increases by 900-1000 mEq",
      "• Serum sodium decreases by 3-4 mEq/L (135-138 mEq/L)",
      "• Osmostat reset to lower threshold (10 mOsm/kg decrease)",
      "",
      "Water Balance:",
      "• Total body water increases by 6-8 liters",
      "• Plasma volume increases by 40-50%",
      "• Interstitial fluid increases",
      "",
      "Mechanisms:",
      "• Increased renin-aldosterone-angiotensin system",
      "• hCG stimulates mineralocorticoid receptors",
      "• ADH threshold lowered by 10 mOsm/kg",
      "• Estrogen effects on fluid retention"
    ]
  },
  {
    title: "Potassium Balance",
    subtitle: "Homeostasis Maintenance",
    content: [
      "Changes:",
      "• Total body potassium increases by 300-350 mEq",
      "• Serum potassium remains normal (3.5-5.0 mEq/L)",
      "• Distributed to fetal-placental unit",
      "",
      "Mechanisms:",
      "• Increased aldosterone levels",
      "• Progesterone has antimineralocorticoid effects",
      "• Balance maintained despite increased excretion",
      "",
      "Clinical Considerations:",
      "• Hypokalemia may occur with hyperemesis",
      "• Monitoring needed with diuretic use",
      "• Risk with pre-existing renal disease"
    ]
  },
  {
    title: "Calcium and Phosphate",
    subtitle: "Mineral Metabolism",
    content: [
      "Calcium:",
      "• Total calcium decreases (due to low albumin)",
      "• Ionized calcium remains normal (1.16-1.32 mmol/L)",
      "• Intestinal absorption doubles",
      "• Urinary excretion increases",
      "",
      "Phosphate:",
      "• Serum levels unchanged (0.8-1.45 mmol/L)",
      "• Increased intestinal absorption",
      "• Increased renal excretion",
      "",
      "Hormonal Regulation:",
      "• PTH levels decrease or remain normal",
      "• 1,25-dihydroxyvitamin D increases 2-fold",
      "• PTHrP from placenta and breast tissue"
    ]
  },
  {
    title: "Renin-Angiotensin-Aldosterone System",
    subtitle: "Paradoxical Activation",
    content: [
      "Changes in RAAS:",
      "• Renin activity increases 5-10 fold",
      "• Angiotensin II increases 2-3 fold",
      "• Aldosterone increases 2-3 fold",
      "• Despite volume expansion",
      "",
      "Mechanisms:",
      "• Decreased vascular responsiveness to angiotensin II",
      "• Progesterone antagonizes aldosterone",
      "• Nitric oxide and prostaglandins counterbalance",
      "• Required to maintain sodium balance",
      "",
      "Clinical Implications:",
      "• Blood pressure remains normal despite RAAS activation",
      "• Loss of resistance in preeclampsia",
      "• ACE inhibitors and ARBs contraindicated"
    ]
  },
  {
    title: "Urinary Tract Infections in Pregnancy",
    subtitle: "Epidemiology and Risk Factors",
    content: [
      "Prevalence:",
      "• Asymptomatic bacteriuria: 2-10%",
      "• Acute cystitis: 1-2%",
      "• Acute pyelonephritis: 1-2%",
      "• 20-40% with bacteriuria develop pyelonephritis if untreated",
      "",
      "Risk Factors:",
      "• Physiologic hydronephrosis and urinary stasis",
      "• Decreased ureteral peristalsis",
      "• Vesicoureteral reflux",
      "• Previous UTI history",
      "• Diabetes mellitus",
      "• Sickle cell trait",
      "• Low socioeconomic status",
      "• Multiparity"
    ]
  },
  {
    title: "Asymptomatic Bacteriuria",
    subtitle: "Diagnosis and Management",
    content: [
      "Definition:",
      "• ≥10⁵ CFU/mL of single organism in asymptomatic patient",
      "• From two consecutive clean-catch specimens",
      "",
      "Screening:",
      "• Universal screening at first prenatal visit",
      "• Urine culture required (not dipstick)",
      "• Repeat if initial negative and high risk",
      "",
      "Common Organisms:",
      "• E. coli (70-80%)",
      "• Klebsiella pneumoniae",
      "• Proteus mirabilis",
      "• Group B Streptococcus",
      "• Enterococcus",
      "",
      "Treatment:",
      "• 3-7 days of antibiotics",
      "• Nitrofurantoin 100 mg BID (avoid term)",
      "• Amoxicillin-clavulanate 500 mg BID",
      "• Cephalexin 500 mg QID",
      "• Test of cure 1-2 weeks post-treatment"
    ]
  },
  {
    title: "Acute Cystitis in Pregnancy",
    subtitle: "Clinical Presentation",
    content: [
      "Symptoms:",
      "• Dysuria",
      "• Urinary frequency and urgency",
      "• Suprapubic pain",
      "• Hematuria",
      "• No fever or systemic symptoms",
      "",
      "Diagnosis:",
      "• Urine dipstick: positive leukocyte esterase/nitrites",
      "• Urinalysis: pyuria (>10 WBC/hpf)",
      "• Urine culture: >10⁵ CFU/mL",
      "",
      "Treatment:",
      "• Same antibiotics as bacteriuria",
      "• 3-7 day course",
      "• Avoid fluoroquinolones and trimethoprim in first trimester",
      "• Symptom resolution in 48-72 hours",
      "• Test of cure mandatory"
    ]
  },
  {
    title: "Acute Pyelonephritis",
    subtitle: "Serious Pregnancy Complication",
    content: [
      "Clinical Features:",
      "• Fever (>38°C) and chills",
      "• Flank pain (unilateral or bilateral)",
      "• Nausea and vomiting",
      "• Costovertebral angle tenderness",
      "• May have lower urinary tract symptoms",
      "",
      "Complications:",
      "• Sepsis and septic shock (10-20%)",
      "• Acute respiratory distress syndrome (2-8%)",
      "• Acute kidney injury",
      "• Anemia",
      "• Preterm labor (7-10%)",
      "• Low birth weight",
      "",
      "Incidence:",
      "• Most common in second and third trimester",
      "• 50% in third trimester",
      "• Right-sided more common (60%)"
    ]
  },
  {
    title: "Pyelonephritis Management",
    subtitle: "Treatment Protocol",
    content: [
      "Initial Management:",
      "• Hospital admission required",
      "• IV hydration",
      "• Blood cultures before antibiotics",
      "• Urine culture",
      "• Complete blood count, metabolic panel",
      "",
      "Antibiotic Therapy:",
      "• IV ceftriaxone 1-2 g daily, OR",
      "• IV cefazolin 1-2 g q8h, OR",
      "• IV ampicillin 2 g q6h + gentamicin (dose by weight)",
      "• Continue IV until afebrile 24-48 hours",
      "• Transition to oral antibiotics for 10-14 day total course",
      "",
      "Monitoring:",
      "• Vital signs q4h",
      "• Urine output monitoring",
      "• Fetal monitoring if viable gestation",
      "• Assess for preterm labor"
    ]
  },
  {
    title: "Recurrent UTI Prevention",
    subtitle: "Prophylactic Strategies",
    content: [
      "Indications for Prophylaxis:",
      "• Recurrent pyelonephritis in pregnancy",
      "• ≥2 episodes of UTI in pregnancy",
      "• Persistent bacteriuria after treatment",
      "",
      "Prophylactic Regimens:",
      "• Nitrofurantoin 50-100 mg once daily at bedtime",
      "• Cephalexin 250-500 mg once daily",
      "• Continue until delivery",
      "",
      "Additional Measures:",
      "• Monthly urine cultures",
      "• Adequate hydration",
      "• Void after intercourse",
      "• Avoid prolonged bladder distension",
      "• Consider imaging postpartum if recurrent"
    ]
  },
  {
    title: "Preeclampsia: Definition and Classification",
    subtitle: "Hypertensive Disorder of Pregnancy",
    content: [
      "Diagnostic Criteria (after 20 weeks):",
      "• Blood pressure ≥140/90 mmHg on two occasions 4h apart, AND",
      "• Proteinuria ≥300 mg/24h or protein:creatinine ≥0.3, OR",
      "• End-organ dysfunction in absence of proteinuria",
      "",
      "Preeclampsia with Severe Features:",
      "• Blood pressure ≥160/110 mmHg",
      "• Thrombocytopenia (<100,000/μL)",
      "• Elevated liver enzymes (2x normal)",
      "• Severe persistent RUQ or epigastric pain",
      "• Renal insufficiency (creatinine >1.1 mg/dL)",
      "• Pulmonary edema",
      "• New-onset cerebral or visual symptoms",
      "",
      "Incidence:",
      "• 3-5% of all pregnancies",
      "• Leading cause of maternal and perinatal morbidity"
    ]
  },
  {
    title: "Preeclampsia Pathophysiology",
    subtitle: "Two-Stage Disease Model",
    content: [
      "Stage 1: Placentation Defect (Early Pregnancy)",
      "• Abnormal trophoblast invasion",
      "• Failed spiral artery remodeling",
      "• Persistent high-resistance uteroplacental circulation",
      "• Placental ischemia and oxidative stress",
      "",
      "Stage 2: Maternal Syndrome (>20 weeks)",
      "• Release of antiangiogenic factors (sFlt-1, sEng)",
      "• Endothelial dysfunction",
      "• Systemic inflammation",
      "• Widespread vasoconstriction",
      "",
      "Key Mediators:",
      "• sFlt-1 (soluble fms-like tyrosine kinase-1): binds VEGF and PlGF",
      "• Soluble endoglin: inhibits TGF-β signaling",
      "• Increased sFlt-1/PlGF ratio: diagnostic marker"
    ]
  },
  {
    title: "Risk Factors for Preeclampsia",
    subtitle: "Maternal and Pregnancy Factors",
    content: [
      "Maternal Risk Factors:",
      "• Nulliparity (relative risk 3.0)",
      "• Previous preeclampsia (RR 7.2)",
      "• Chronic hypertension (RR 3.8)",
      "• Pregestational diabetes (RR 3.6)",
      "• Multiple gestation (RR 2.9)",
      "• Maternal age >40 years (RR 2.0)",
      "• Obesity (BMI >30: RR 2.1)",
      "• Thrombophilias",
      "• Chronic kidney disease (RR 3.0)",
      "• Systemic lupus erythematosus (RR 9.7)",
      "• Family history of preeclampsia",
      "",
      "Pregnancy Factors:",
      "• Multifetal gestation",
      "• Molar pregnancy",
      "• Hydrops fetalis",
      "• New paternity"
    ]
  },
  {
    title: "Renal Manifestations of Preeclampsia",
    subtitle: "Glomerular Endotheliosis",
    content: [
      "Pathology:",
      "• Glomerular endotheliosis (pathognomonic)",
      "• Swelling of endothelial cells",
      "• Loss of fenestrations",
      "• Narrowing of capillary lumens",
      "• Mesangial cell interposition",
      "• Subendothelial protein deposits",
      "• No immune complex deposition",
      "",
      "Functional Changes:",
      "• Decreased GFR (25-30% reduction)",
      "• Decreased renal blood flow",
      "• Increased renal vascular resistance",
      "• Proteinuria (often nephrotic range)",
      "• Hyperuricemia (due to decreased clearance)",
      "• Sodium retention",
      "",
      "Resolution:",
      "• Lesions resolve completely postpartum",
      "• GFR normalizes within 6-12 weeks"
    ]
  },
  {
    title: "Proteinuria in Preeclampsia",
    subtitle: "Quantification and Significance",
    content: [
      "Diagnostic Thresholds:",
      "• ≥300 mg/24 hour urine collection",
      "• Protein:creatinine ratio ≥0.3",
      "• Dipstick 1+ (if quantitative unavailable)",
      "",
      "Severity Spectrum:",
      "• Mild: 300-5,000 mg/24h",
      "• Nephrotic range: >3,500 mg/24h (20-25% of cases)",
      "• No longer used to classify severity",
      "",
      "Timing and Pattern:",
      "• May be absent at initial diagnosis",
      "• Develops later in 10-20% of cases",
      "• Degree does not correlate with outcome",
      "• Worsens with disease progression",
      "",
      "Clinical Implications:",
      "• Presence confirms diagnosis",
      "• Absence doesn't exclude preeclampsia",
      "• Nephrotic-range associated with hypoalbuminemia"
    ]
  },
  {
    title: "Acute Kidney Injury in Preeclampsia",
    subtitle: "Severe Complication",
    content: [
      "Incidence:",
      "• 1-2% of preeclampsia cases",
      "• 7-15% of severe preeclampsia",
      "• Leading cause of pregnancy-related AKI",
      "",
      "Mechanisms:",
      "• Acute tubular necrosis",
      "• Cortical necrosis (rare but severe)",
      "• Volume depletion from capillary leak",
      "• Hemolysis and hemoglobinuria",
      "• Disseminated intravascular coagulation",
      "",
      "Risk Factors:",
      "• HELLP syndrome",
      "• Abruptio placentae",
      "• Postpartum hemorrhage",
      "• Sepsis",
      "",
      "Management:",
      "• Delivery of fetus",
      "• Supportive care",
      "• Fluid management (avoid overload)",
      "• Dialysis if indicated (5-10% of AKI)"
    ]
  },
  {
    title: "HELLP Syndrome",
    subtitle: "Severe Preeclampsia Variant",
    content: [
      "Definition:",
      "• Hemolysis",
      "• Elevated Liver enzymes",
      "• Low Platelet count",
      "",
      "Diagnostic Criteria:",
      "• Hemolysis: schistocytes, bilirubin >1.2 mg/dL, LDH >600 U/L",
      "• AST or ALT >2x upper limit normal",
      "• Platelets <100,000/μL",
      "",
      "Incidence:",
      "• 0.5-0.9% of all pregnancies",
      "• 10-20% of severe preeclampsia cases",
      "• Peak at 27-37 weeks gestation",
      "",
      "Renal Involvement:",
      "• AKI in 3-15% of cases",
      "• Oliguria common",
      "• Proteinuria often severe",
      "• May require dialysis",
      "",
      "Complications:",
      "• Placental abruption (16%)",
      "• DIC (15-20%)",
      "• Acute renal failure (3-15%)",
      "• Pulmonary edema (6-11%)",
      "• Liver hemorrhage/rupture (1-2%)",
      "• Maternal mortality (1-3%)"
    ]
  },
  {
    title: "Preeclampsia Management",
    subtitle: "Definitive Treatment",
    content: [
      "Definitive Treatment:",
      "• Delivery is the only cure",
      "• Timing based on gestational age and severity",
      "",
      "Expectant Management (if <34 weeks without severe features):",
      "• Close maternal and fetal monitoring",
      "• Antepartum corticosteroids for fetal lung maturity",
      "• Antihypertensive therapy",
      "• Serial labs: CBC, creatinine, LFTs, uric acid",
      "• Daily fetal monitoring",
      "",
      "Delivery Indications:",
      "• ≥37 weeks with preeclampsia",
      "• ≥34 weeks with severe features",
      "• Any gestational age with:",
      "  - Uncontrolled severe hypertension",
      "  - Eclampsia",
      "  - Pulmonary edema",
      "  - Abruptio placentae",
      "  - DIC",
      "  - Non-reassuring fetal status"
    ]
  },
  {
    title: "Antihypertensive Therapy in Preeclampsia",
    subtitle: "Blood Pressure Control",
    content: [
      "Goal:",
      "• BP 140-150/90-100 mmHg",
      "• Prevent stroke and cardiovascular complications",
      "• Avoid excessive lowering (placental perfusion)",
      "",
      "First-Line Acute Treatment (BP ≥160/110):",
      "• Labetalol: 20 mg IV, then 40-80 mg q10min (max 300 mg)",
      "• Hydralazine: 5-10 mg IV q20min (max 30 mg)",
      "• Nifedipine IR: 10-20 mg PO q20min (max 50 mg)",
      "",
      "Maintenance Therapy:",
      "• Labetalol: 200-400 mg PO BID-TID",
      "• Nifedipine XL: 30-120 mg PO daily",
      "• Methyldopa: 250-500 mg PO TID-QID",
      "",
      "Contraindicated:",
      "• ACE inhibitors",
      "• Angiotensin receptor blockers",
      "• Direct renin inhibitors",
      "• Atenolol (IUGR risk)"
    ]
  },
  {
    title: "Magnesium Sulfate for Seizure Prophylaxis",
    subtitle: "Standard of Care",
    content: [
      "Indications:",
      "• Preeclampsia with severe features",
      "• During labor and delivery with preeclampsia",
      "• Eclampsia treatment",
      "",
      "Dosing:",
      "• Loading: 4-6 g IV over 15-20 minutes",
      "• Maintenance: 1-2 g/hour continuous infusion",
      "• Continue 24 hours postpartum",
      "",
      "Mechanism:",
      "• Cerebral vasodilation",
      "• Neuroprotection",
      "• Reduced cerebral ischemia",
      "• NMDA receptor antagonism",
      "",
      "Monitoring:",
      "• Serum magnesium levels q4-6h (therapeutic 4-8 mg/dL)",
      "• Deep tendon reflexes hourly",
      "• Urine output >25 mL/hour",
      "• Respiratory rate >12/minute",
      "",
      "Toxicity:",
      "• Loss of reflexes: 9-12 mg/dL",
      "• Respiratory depression: >15 mg/dL",
      "• Cardiac arrest: >25 mg/dL",
      "• Antidote: Calcium gluconate 1 g IV"
    ]
  },
  {
    title: "Eclampsia",
    subtitle: "Seizures in Pregnancy",
    content: [
      "Definition:",
      "• New-onset grand mal seizures in preeclampsia",
      "• No other neurological cause",
      "",
      "Incidence:",
      "• 0.5-2% of preeclampsia cases",
      "• 60% occur antepartum",
      "• 20% during labor",
      "• 20% within 48h postpartum (can occur up to 4 weeks)",
      "",
      "Clinical Features:",
      "• Tonic-clonic seizures (1-2 minutes)",
      "• Postictal confusion",
      "• May have aura: headache, visual changes",
      "• 30-40% have no prodromal symptoms",
      "",
      "Complications:",
      "• Maternal: aspiration, stroke, ICH, death (0-2%)",
      "• Placental abruption (10%)",
      "• Fetal compromise",
      "",
      "Management:",
      "• Airway protection",
      "• Magnesium sulfate (loading + maintenance)",
      "• Blood pressure control",
      "• Delivery after stabilization"
    ]
  },
  {
    title: "Long-Term Renal Outcomes After Preeclampsia",
    subtitle: "Cardiovascular and Renal Risk",
    content: [
      "Increased Future Risk:",
      "• Chronic hypertension (RR 3.7)",
      "• Chronic kidney disease (RR 4.7)",
      "• End-stage renal disease (RR 4.3-6.4)",
      "• Cardiovascular disease (RR 2.3)",
      "• Stroke (RR 1.8)",
      "• Metabolic syndrome",
      "",
      "Mechanism:",
      "• Preeclampsia unmasks subclinical renal disease",
      "• Endothelial dysfunction persists",
      "• Shared risk factors",
      "• Possible permanent vascular damage",
      "",
      "Postpartum Follow-Up:",
      "• BP check at 1 week and 6-8 weeks postpartum",
      "• Urinalysis and creatinine at 3 months",
      "• Annual BP monitoring",
      "• Cardiovascular risk assessment",
      "• Lifestyle modification counseling",
      "• Consider low-dose aspirin for future pregnancies"
    ]
  },
  {
    title: "Chronic Kidney Disease in Pregnancy",
    subtitle: "Definition and Classification",
    content: [
      "Definition of CKD:",
      "• Kidney damage or GFR <60 mL/min/1.73m² for ≥3 months",
      "• Pre-pregnancy diagnosis essential",
      "",
      "Prevalence:",
      "• 0.03-0.12% of pregnancies",
      "• Increasing due to delayed childbearing",
      "",
      "CKD Stage Classification:",
      "• Stage 1: GFR ≥90 + kidney damage",
      "• Stage 2: GFR 60-89 + kidney damage (Mild CKD)",
      "• Stage 3: GFR 30-59 (Moderate CKD)",
      "• Stage 4: GFR 15-29 (Severe CKD)",
      "• Stage 5: GFR <15 or dialysis (ESRD)",
      "",
      "Pregnancy Outcomes Correlate with:",
      "• Baseline renal function",
      "• Degree of proteinuria",
      "• Presence of hypertension",
      "• Underlying kidney disease etiology"
    ]
  },
  {
    title: "CKD and Pregnancy Outcomes",
    subtitle: "Maternal and Fetal Risks",
    content: [
      "Maternal Complications by CKD Stage:",
      "• Stage 1-2 (GFR >60): Usually good outcomes",
      "  - Preeclampsia: 20-25%",
      "  - Renal function decline: 10%",
      "• Stage 3 (GFR 30-59): Moderate risk",
      "  - Preeclampsia: 40-50%",
      "  - Renal function decline: 40-50%",
      "• Stage 4-5 (GFR <30): High risk",
      "  - Preeclampsia: 60-75%",
      "  - Renal function decline: 50-70%",
      "  - Progression to ESRD: 35%",
      "",
      "Fetal Complications:",
      "• Intrauterine growth restriction (25-37%)",
      "• Preterm birth (30-80% depending on stage)",
      "• Low birth weight",
      "• Perinatal mortality (increased 3-10 fold)",
      "• Risk increases with worse baseline function"
    ]
  },
  {
    title: "Management of CKD in Pregnancy",
    subtitle: "Preconception and Antenatal Care",
    content: [
      "Preconception Counseling:",
      "• Assess baseline renal function (Cr, GFR, proteinuria)",
      "• Optimize blood pressure control",
      "• Switch teratogenic medications (ACEi, ARBs)",
      "• Screen for and treat anemia",
      "• Assess cardiovascular risk",
      "• Discuss pregnancy risks and timing",
      "",
      "Optimal Timing:",
      "• Stable kidney function for 6 months",
      "• Creatinine <1.5 mg/dL preferred",
      "• Proteinuria <1 g/day preferred",
      "• Blood pressure <140/90 on safe medications",
      "",
      "Antenatal Management:",
      "• Multidisciplinary care (nephrologist, MFM, dietitian)",
      "• Monthly renal function assessment (Cr, proteinuria)",
      "• Every 2 weeks if GFR <60",
      "• Serial fetal growth ultrasounds q3-4 weeks",
      "• Antenatal testing from 32 weeks",
      "• Low-dose aspirin for preeclampsia prophylaxis"
    ]
  },
  {
    title: "Hypertension Management in CKD",
    subtitle: "Blood Pressure Control",
    content: [
      "Target Blood Pressure:",
      "• <140/90 mmHg (previous <130/80)",
      "• Balance maternal and fetal risks",
      "• Avoid excessive reduction (placental perfusion)",
      "",
      "Safe Antihypertensives:",
      "• Methyldopa: 250-1000 mg PO BID-QID (first-line)",
      "• Labetalol: 200-800 mg PO BID-TID",
      "• Long-acting nifedipine: 30-120 mg PO daily",
      "• Hydralazine: 25-100 mg PO QID (adjunct)",
      "",
      "Contraindicated (discontinue pre-pregnancy):",
      "• ACE inhibitors (renal dysgenesis, oligohydramnios)",
      "• ARBs (same as ACEi)",
      "• Direct renin inhibitors",
      "• Spironolactone (antiandrogen effects)",
      "• Atenolol (IUGR)",
      "",
      "Monitoring:",
      "• Home BP monitoring",
      "• Weekly or biweekly BP checks",
      "• Watch for superimposed preeclampsia"
    ]
  },
  {
    title: "Proteinuria in CKD Pregnancy",
    subtitle: "Monitoring and Interpretation",
    content: [
      "Baseline Assessment:",
      "• 24-hour urine protein before pregnancy or early pregnancy",
      "• Protein:creatinine ratio",
      "• Essential for distinguishing superimposed preeclampsia",
      "",
      "Expected Changes:",
      "• Proteinuria often increases 2-3 fold in pregnancy",
      "• Due to increased GFR and glomerular permeability",
      "• Increase alone doesn't indicate disease progression",
      "",
      "Monitoring:",
      "• Monthly 24h urine protein or P:C ratio",
      "• More frequent if increasing",
      "",
      "Superimposed Preeclampsia:",
      "• New hypertension or worsening hypertension",
      "• Sudden increase in proteinuria (>3g/24h or doubling)",
      "• Thrombocytopenia, elevated liver enzymes",
      "• New symptoms (headache, RUQ pain, visual changes)",
      "• Difficult to distinguish from CKD progression",
      "• sFlt-1/PlGF ratio may help diagnose"
    ]
  },
  {
    title: "Specific Renal Diseases: Diabetic Nephropathy",
    subtitle: "Pregnancy Considerations",
    content: [
      "Background:",
      "• Most common cause of CKD in pregnancy",
      "• 2-5% of diabetic women have nephropathy",
      "",
      "Risk Assessment:",
      "• Good prognosis if Cr <1.5 mg/dL, proteinuria <3g/day",
      "• Higher risk if advanced stage or poor glycemic control",
      "",
      "Glycemic Control:",
      "• Target HbA1c <6-6.5% preconception",
      "• Pregnancy targets: fasting <95 mg/dL, 1h post <140 mg/dL",
      "• Insulin is treatment of choice",
      "• Continuous glucose monitoring helpful",
      "",
      "Complications:",
      "• Diabetic retinopathy progression (10-55%)",
      "• Nephropathy progression (15-45%)",
      "• Preeclampsia (25-35%)",
      "• Preterm delivery (30-60%)",
      "• Congenital anomalies if poor control",
      "• Macrosomia vs IUGR",
      "",
      "Monitoring:",
      "• Monthly ophthalmology exams",
      "• Biweekly renal function from 20 weeks",
      "• Frequent fetal surveillance"
    ]
  },
  {
    title: "Lupus Nephritis in Pregnancy",
    subtitle: "Autoimmune Renal Disease",
    content: [
      "Background:",
      "• 35-55% of SLE patients develop nephritis",
      "• High-risk pregnancy requiring subspecialist care",
      "",
      "Optimal Timing for Pregnancy:",
      "• Lupus quiescent for 6-12 months",
      "• Stable renal function (Cr <1.5 mg/dL)",
      "• Proteinuria <0.5 g/day",
      "• No active extrarenal lupus",
      "• On pregnancy-safe medications",
      "",
      "Pregnancy Complications:",
      "• Lupus flare: 25-65% (more if active disease)",
      "• Nephritis flare: 10-30%",
      "• Preeclampsia: 20-35%",
      "• Thrombotic events (if antiphospholipid antibodies)",
      "• Pregnancy loss: 15-20%",
      "• Preterm birth: 35-50%",
      "• IUGR: 30%",
      "• Neonatal lupus (if anti-Ro/La positive): 2-5%",
      "• Congenital heart block: 1-2%",
      "",
      "Distinguishing Lupus Flare vs Preeclampsia:",
      "• Active urinary sediment (RBC casts) → lupus",
      "• Low C3/C4, high anti-dsDNA → lupus",
      "• Thrombocytopenia + elevated LFTs → preeclampsia",
      "• May require kidney biopsy in severe cases"
    ]
  },
  {
    title: "Lupus Nephritis Management",
    subtitle: "Treatment During Pregnancy",
    content: [
      "Safe Medications:",
      "• Hydroxychloroquine 200-400 mg daily (continue always)",
      "• Prednisone ≤20 mg daily for maintenance",
      "• Azathioprine ≤2 mg/kg/day",
      "• Tacrolimus 1-5 mg BID (if needed)",
      "• Low-dose aspirin 81 mg daily",
      "• Heparin/LMWH if antiphospholipid syndrome",
      "",
      "Contraindicated:",
      "• Mycophenolate mofetil (teratogenic)",
      "• Cyclophosphamide (except life-threatening disease)",
      "• Methotrexate",
      "",
      "Treating Active Flare:",
      "• Prednisone 0.5-1 mg/kg/day",
      "• IV methylprednisolone 500-1000 mg daily x3 if severe",
      "• Add/optimize azathioprine or tacrolimus",
      "• Consider IVIG, plasmapheresis for severe cases",
      "",
      "Monitoring:",
      "• Monthly labs: CBC, metabolic panel, complement, anti-dsDNA",
      "• Biweekly after 20 weeks",
      "• Proteinuria monthly",
      "• Fetal growth ultrasounds q3-4 weeks",
      "• Fetal echocardiography at 18-24 weeks (if anti-Ro/La+)"
    ]
  },
  {
    title: "IgA Nephropathy and Glomerulonephritis",
    subtitle: "Primary Glomerular Diseases",
    content: [
      "IgA Nephropathy:",
      "• Most common primary glomerulonephritis worldwide",
      "• Usually good pregnancy outcomes if mild disease",
      "• Risk if Cr >1.4 mg/dL or proteinuria >1 g/day",
      "• May have gross hematuria with infections",
      "",
      "Membranous Nephropathy:",
      "• Usually good outcomes if normal function",
      "• Thromboembolic risk if nephrotic syndrome",
      "• Anticoagulation if albumin <2.5 g/dL",
      "",
      "Focal Segmental Glomerulosclerosis (FSGS):",
      "• Proteinuria often worsens significantly",
      "• Distinguish from preeclampsia challenging",
      "• Higher risk of renal function decline",
      "• 30-50% develop preeclampsia",
      "",
      "Minimal Change Disease:",
      "• Rare in pregnancy",
      "• Nephrotic syndrome common",
      "• Responds to corticosteroids",
      "• Good maternal and fetal outcomes",
      "",
      "General Principles:",
      "• Avoid immunosuppression if possible",
      "• Use prednisone/azathioprine if needed",
      "• Monitor for complications",
      "• May need biopsy if unclear diagnosis"
    ]
  },
  {
    title: "Polycystic Kidney Disease",
    subtitle: "Genetic Disorder in Pregnancy",
    content: [
      "Autosomal Dominant PKD:",
      "• Most common inherited kidney disease",
      "• Prevalence 1:400-1:1000",
      "• Usually diagnosed in adulthood",
      "",
      "Pregnancy Considerations:",
      "• Usually well-tolerated if normal renal function",
      "• 30-40% develop hypertension in pregnancy",
      "• Preeclampsia risk: 25-40%",
      "• UTI risk increased",
      "• Cyst hemorrhage or infection possible",
      "",
      "Complications if Advanced CKD:",
      "• Higher preeclampsia risk (50-75%)",
      "• Renal function decline",
      "• IUGR and preterm birth",
      "",
      "Management:",
      "• Blood pressure monitoring and control",
      "• Screen for bacteriuria",
      "• Adequate hydration",
      "• Avoid NSAIDs",
      "• Genetic counseling (50% transmission risk)",
      "• Consider prenatal diagnosis if desired",
      "",
      "Aneurysm Risk:",
      "• 5-10% have intracranial aneurysms",
      "• Higher if family history",
      "• MRA screening controversial in pregnancy"
    ]
  },
  {
    title: "Reflux Nephropathy and Congenital Anomalies",
    subtitle: "Structural Renal Disease",
    content: [
      "Vesicoureteral Reflux (VUR):",
      "• Common cause of CKD in young women",
      "• Due to childhood reflux and recurrent infections",
      "",
      "Pregnancy Outcomes:",
      "• Good if preserved renal function",
      "• Increased UTI and pyelonephritis risk (30-50%)",
      "• May require prophylactic antibiotics",
      "• Close monitoring for infections",
      "",
      "Solitary Kidney:",
      "• Congenital agenesis or previous nephrectomy",
      "• Usually excellent pregnancy outcomes",
      "• Single kidney hyperfiltration and growth",
      "• Monitor for proteinuria and hypertension",
      "• May have 10-15% risk of preeclampsia",
      "",
      "Horseshoe Kidney:",
      "• Usually asymptomatic",
      "• Increased UTI risk",
      "• Increased hydronephrosis risk",
      "• Usually good outcomes",
      "",
      "Management:",
      "• Preconception renal function assessment",
      "• Screen for and promptly treat UTIs",
      "• Monitor proteinuria and blood pressure",
      "• Avoid nephrotoxic medications"
    ]
  },
  {
    title: "Kidney Transplant and Pregnancy",
    subtitle: "Special Considerations",
    content: [
      "Pregnancy After Transplant:",
      "• Over 15,000 successful pregnancies reported",
      "• Pregnancy generally safe if stable graft function",
      "",
      "Optimal Timing:",
      "• Wait 1-2 years post-transplant",
      "• Stable graft function (Cr <1.5 mg/dL)",
      "• No acute rejection in past year",
      "• Proteinuria <0.5 g/day",
      "• Blood pressure <140/90 on safe medications",
      "• Stable immunosuppression",
      "",
      "Pregnancy Outcomes:",
      "• Live birth rate: 70-80%",
      "• Preeclampsia: 25-30%",
      "• Preterm birth: 45-60%",
      "• IUGR: 20-30%",
      "• Cesarean delivery: 50-60%",
      "",
      "Risks:",
      "• Acute rejection: 5-10% (similar to non-pregnant)",
      "• Graft loss: 2-3%",
      "• Infection (especially CMV, UTI)",
      "• Long-term graft function usually unchanged",
      "• Slight increase in chronic rejection risk"
    ]
  },
  {
    title: "Immunosuppression in Transplant Pregnancy",
    subtitle: "Medication Safety",
    content: [
      "Safe Immunosuppression:",
      "• Prednisone: continue (usually ≤15 mg/day)",
      "• Tacrolimus: continue (adjust levels)",
      "  - Target trough 5-10 ng/mL",
      "  - Monitor levels every 2-4 weeks",
      "• Azathioprine: continue (≤2 mg/kg/day)",
      "• Cyclosporine: continue if needed (adjust levels)",
      "",
      "Contraindicated:",
      "• Mycophenolate mofetil/mycophenolic acid",
      "  - Discontinue 6 weeks before conception",
      "  - Switch to azathioprine",
      "• Sirolimus/everolimus",
      "  - Discontinue 12 weeks before conception",
      "",
      "Monitoring:",
      "• Tacrolimus/cyclosporine levels q2-4 weeks",
      "• CBC, metabolic panel monthly",
      "• Tacrolimus absorption decreases in pregnancy",
      "• May need dose increases",
      "",
      "Neonatal Effects:",
      "• Transient lymphopenia possible",
      "• Transient anemia possible",
      "• No long-term developmental issues",
      "• Breastfeeding safe with most immunosuppressants"
    ]
  },
  {
    title: "Dialysis in Pregnancy",
    subtitle: "Pregnancy on Renal Replacement Therapy",
    content: [
      "Fertility on Dialysis:",
      "• Severely reduced due to uremia",
      "• Conception rate <1% annually",
      "• Increasing with improved dialysis adequacy",
      "• Most pregnancies unplanned",
      "",
      "Historical Outcomes:",
      "• Live birth rate <25% before 1990",
      "• Live birth rate 40-50% in 1990-2000",
      "• Live birth rate 60-80% with intensive dialysis (>2010)",
      "",
      "Complications:",
      "• Polyhydramnios (40-70%)",
      "• Preeclampsia (25-75%)",
      "• Preterm birth (80-90%)",
      "• IUGR (30-60%)",
      "• Maternal anemia",
      "• Infection",
      "• Volume management challenges",
      "",
      "Improved Outcomes Associated With:",
      "• Intensive dialysis (≥6 days/week)",
      "• Target predialysis BUN <50 mg/dL",
      "• Extended hours (20-36 hours/week)",
      "• Nocturnal dialysis",
      "• Early pregnancy diagnosis"
    ]
  },
  {
    title: "Hemodialysis Management in Pregnancy",
    subtitle: "Intensive Dialysis Protocol",
    content: [
      "Dialysis Prescription:",
      "• Increase frequency to 5-7 days/week (or 6 nights/week)",
      "• Total weekly hours: 20-36 hours",
      "• Individualize based on residual renal function",
      "• Shorter, more frequent sessions better tolerated",
      "",
      "Targets:",
      "• Predialysis BUN <45-50 mg/dL (ideally <17 mmol/L)",
      "• Postdialysis BUN <35 mg/dL",
      "• Avoid rapid ultrafiltration (hypotension risk)",
      "• Keep sessions <4 hours if possible",
      "",
      "Fluid Management:",
      "• Dry weight increases ~0.5 kg/week (0.4 kg/week in 3rd trimester)",
      "• Avoid excessive ultrafiltration",
      "• Maintain euvolemia",
      "• Monitor for polyhydramnios",
      "",
      "Dialysate:",
      "• Bicarbonate-based dialysate",
      "• Consider higher bicarbonate concentration (30-35 mmol/L)",
      "• Calcium 1.25-1.5 mmol/L",
      "• Potassium 2-3 mmol/L"
    ]
  },
  {
    title: "Peritoneal Dialysis in Pregnancy",
    subtitle: "Alternative Modality",
    content: [
      "Feasibility:",
      "• Less commonly used than hemodialysis",
      "• Successful pregnancies reported",
      "• Allows more continuous clearance",
      "",
      "Advantages:",
      "• Steady-state biochemistry",
      "• Avoid hemodynamic instability",
      "• Better volume control",
      "• Home-based therapy",
      "• May be better for residual renal function",
      "",
      "Challenges:",
      "• Increasing abdominal girth",
      "• Reduced fill volumes (comfort, respiratory)",
      "• Peritonitis risk (increased?)",
      "• Difficult to achieve adequate clearance",
      "• May need conversion to hemodialysis in late pregnancy",
      "",
      "Management:",
      "• Increase exchange frequency",
      "• Reduce fill volumes as needed",
      "• Automated PD preferred",
      "• Strict aseptic technique",
      "• Low threshold for treating peritonitis",
      "• Monitor adequacy (Kt/V)",
      "",
      "Delivery:",
      "• Drain abdomen before cesarean section",
      "• Can usually resume PD 1-2 weeks postpartum"
    ]
  },
  {
    title: "Supportive Management During Dialysis Pregnancy",
    subtitle: "Anemia and Nutrition",
    content: [
      "Anemia Management:",
      "• Target hemoglobin 10-11 g/dL",
      "• Erythropoiesis-stimulating agents (ESA) safe",
      "• Increase ESA dose by 50-100%",
      "• Epoetin alfa or darbepoetin",
      "• IV iron supplementation",
      "• Target ferritin >200 ng/mL, TSAT >20%",
      "• Blood transfusion if Hb <7 g/dL or symptomatic",
      "",
      "Nutritional Requirements:",
      "• Protein: 1.5-1.8 g/kg/day (plus fetal needs)",
      "• Additional 10-20 g protein daily",
      "• Calories: 25-35 kcal/kg/day + 300 kcal/day",
      "• Monitor for malnutrition (common)",
      "",
      "Supplementation:",
      "• Prenatal vitamins",
      "• Folate 1-5 mg daily (higher due to dialysis losses)",
      "• Vitamin B6, B12, C (water-soluble losses)",
      "• Vitamin D to maintain 25-OH-D >30 ng/mL",
      "• Phosphate binders as needed",
      "",
      "Monitoring:",
      "• Weekly or biweekly labs",
      "• Nutritionist involvement essential"
    ]
  },
  {
    title: "Pregnancy in Dialysis: Monitoring and Delivery",
    subtitle: "Fetal Surveillance",
    content: [
      "Maternal Monitoring:",
      "• Weekly labs: BUN, creatinine, electrolytes, bicarbonate",
      "• Biweekly CBC",
      "• Monthly calcium, phosphate, PTH",
      "• Blood pressure before and after each dialysis",
      "",
      "Fetal Monitoring:",
      "• Confirm viability early",
      "• Ultrasound for dating",
      "• Growth scans every 2-3 weeks from 24 weeks",
      "• Doppler studies if IUGR",
      "• Antenatal testing (NST/BPP) from 32 weeks",
      "• 2-3 times weekly in third trimester",
      "• Monitor amniotic fluid volume",
      "",
      "Timing of Delivery:",
      "• Individualized based on maternal-fetal status",
      "• Typically 36-37 weeks if stable",
      "• Earlier if complications",
      "• Mode: based on obstetric indications",
      "",
      "Peripartum Management:",
      "• Dialysis day before delivery if possible",
      "• Avoid heparin before cesarean",
      "• Fetal monitoring during labor",
      "• Platelet transfusion if dysfunctional platelets"
    ]
  },
  {
    title: "Acute Kidney Injury in Pregnancy",
    subtitle: "Causes and Timing",
    content: [
      "Incidence:",
      "• 1-2.8% of pregnancies (developed countries)",
      "• Up to 15% in developing countries",
      "• Leading cause of maternal mortality globally",
      "",
      "Timing and Causes:",
      "First Trimester:",
      "• Hyperemesis gravidarum (volume depletion)",
      "• Septic abortion",
      "• Ectopic pregnancy",
      "",
      "Second/Third Trimester:",
      "• Preeclampsia/HELLP syndrome (most common)",
      "• Acute fatty liver of pregnancy",
      "• Placental abruption",
      "• Sepsis",
      "",
      "Postpartum:",
      "• Postpartum hemorrhage (most common)",
      "• Preeclampsia/HELLP",
      "• Hemolytic uremic syndrome (atypical HUS)",
      "• Thrombotic thrombocytopenic purpura (TTP)"
    ]
  },
  {
    title: "Acute Fatty Liver of Pregnancy",
    subtitle: "Rare but Life-Threatening",
    content: [
      "Incidence:",
      "• 1 in 7,000-20,000 pregnancies",
      "• Usually third trimester (30-38 weeks)",
      "",
      "Pathophysiology:",
      "• Mitochondrial dysfunction in fatty acid oxidation",
      "• Often associated with fetal LCHAD deficiency",
      "• Microvesicular hepatic steatosis",
      "",
      "Clinical Features:",
      "• Nausea, vomiting, abdominal pain",
      "• Jaundice (progressive)",
      "• Hypoglycemia",
      "• Coagulopathy",
      "• Hepatic encephalopathy (late)",
      "",
      "Laboratory Findings:",
      "• Elevated transaminases (300-500 U/L, not as high as HELLP)",
      "• Hyperbilirubinemia (direct)",
      "• Prolonged PT/INR",
      "• Thrombocytopenia (mild)",
      "• Hypoglycemia",
      "• Elevated ammonia",
      "• Leukocytosis",
      "• Acute kidney injury (50-60%)",
      "• Elevated creatinine, oliguria",
      "• DIC in severe cases"
    ]
  },
  {
    title: "AFLP Diagnosis and Management",
    subtitle: "Swansea Criteria",
    content: [
      "Swansea Diagnostic Criteria (6 or more in absence of other explanation):",
      "• Vomiting",
      "• Abdominal pain",
      "• Polydipsia/polyuria",
      "• Encephalopathy",
      "• Elevated bilirubin >14 μmol/L (0.8 mg/dL)",
      "• Hypoglycemia <4 mmol/L (72 mg/dL)",
      "• Elevated uric acid >340 μmol/L (5.7 mg/dL)",
      "• Leukocytosis >11,000/μL",
      "• AST or ALT >42 U/L",
      "• Elevated ammonia >47 μmol/L",
      "• Renal impairment (creatinine >150 μmol/L, 1.7 mg/dL)",
      "• Coagulopathy (PT >14 sec or APTT >34 sec)",
      "• Ascites or bright liver on ultrasound",
      "• Microvesicular steatosis on liver biopsy",
      "",
      "Management:",
      "• Immediate delivery (only cure)",
      "• ICU admission",
      "• Supportive care: glucose, FFP, cryoprecipitate",
      "• Correct coagulopathy before delivery",
      "• Monitor for hepatic failure, DIC",
      "",
      "Prognosis:",
      "• Maternal mortality 10-20% (historically higher)",
      "• Perinatal mortality 10-30%",
      "• Recovery usually complete postpartum"
    ]
  },
  {
    title: "Thrombotic Microangiopathies",
    subtitle: "TTP and Atypical HUS",
    content: [
      "Differential Diagnosis:",
      "• Thrombotic thrombocytopenic purpura (TTP)",
      "• Hemolytic uremic syndrome (HUS)",
      "• Atypical HUS (aHUS)",
      "• HELLP syndrome",
      "• All cause: thrombocytopenia, hemolysis, AKI",
      "",
      "TTP:",
      "• ADAMTS13 deficiency (<10%)",
      "• Neurological symptoms prominent",
      "• Fever common",
      "• Less severe renal involvement",
      "• Can occur any trimester or postpartum",
      "• Treatment: plasma exchange urgently",
      "",
      "Atypical HUS:",
      "• Complement dysregulation",
      "• Severe AKI predominates",
      "• Usually postpartum (days to weeks)",
      "• Neurological symptoms less common",
      "• Treatment: eculizumab (complement C5 inhibitor)",
      "• May progress to ESRD (50-70% without treatment)",
      "",
      "Distinguishing from HELLP:",
      "• Timing: aHUS/TTP often >48-72h postpartum",
      "• Persistence/worsening after delivery",
      "• More severe hemolysis in TMA",
      "• Neurologic symptoms favor TTP",
      "• Severe AKI favors aHUS"
    ]
  },
  {
    title: "Cortical Necrosis",
    subtitle: "Catastrophic Renal Event",
    content: [
      "Definition:",
      "• Ischemic necrosis of renal cortex",
      "• Rare but devastating complication",
      "",
      "Causes:",
      "• Severe placental abruption (most common)",
      "• Severe preeclampsia/HELLP",
      "• Septic abortion",
      "• Amniotic fluid embolism",
      "• Prolonged shock",
      "• DIC",
      "",
      "Clinical Features:",
      "• Abrupt anuria",
      "• Gross hematuria",
      "• Flank pain",
      "• Following obstetric catastrophe",
      "",
      "Diagnosis:",
      "• CT: hypodense cortex with sparing of medulla",
      "• Ultrasound: hyperechoic rim",
      "• May have cortical calcifications (late)",
      "",
      "Prognosis:",
      "• Usually irreversible",
      "• 20-40% require permanent dialysis",
      "• Partial recovery possible in some cases",
      "• Depends on extent of necrosis (patchy vs diffuse)",
      "",
      "Management:",
      "• Supportive care",
      "• Dialysis as needed",
      "• Treat underlying cause"
    ]
  },
  {
    title: "Nephrolithiasis in Pregnancy",
    subtitle: "Kidney Stones",
    content: [
      "Incidence:",
      "• 0.03-0.35% of pregnancies",
      "• Similar to non-pregnant women",
      "• Can occur any trimester",
      "",
      "Risk Factors:",
      "• Personal or family history",
      "• Dehydration",
      "• Urinary stasis",
      "• Hypercalciuria (present in 30% of pregnancies)",
      "",
      "Clinical Presentation:",
      "• Flank pain (often severe)",
      "• Hematuria (90%)",
      "• Nausea and vomiting",
      "• Dysuria if stone at UVJ",
      "",
      "Differential Diagnosis:",
      "• Appendicitis",
      "• Cholecystitis",
      "• Placental abruption",
      "• Preterm labor",
      "• Pyelonephritis",
      "",
      "Complications:",
      "• UTI/pyelonephritis (most common)",
      "• Urosepsis",
      "• Preterm labor (30%)",
      "• Hydronephrosis",
      "• Rarely AKI"
    ]
  },
  {
    title: "Nephrolithiasis Diagnosis and Management",
    subtitle: "Treatment Approach",
    content: [
      "Diagnosis:",
      "• Urinalysis: hematuria",
      "• Ultrasound: first-line imaging (safe)",
      "  - May show stone, hydronephrosis",
      "  - Sensitivity 60-70% (lower than CT)",
      "• MRI urography: if ultrasound inconclusive",
      "• Limited CT: if diagnosis uncertain and management affected",
      "",
      "Conservative Management (first-line):",
      "• Hydration (IV if needed)",
      "• Analgesia (acetaminophen, opioids if needed)",
      "• Alpha-blockers (tamsulosin) may help passage",
      "• 70-80% pass spontaneously",
      "• Antiemetics",
      "• Treat UTI if present",
      "",
      "Interventional Treatment (if conservative fails):",
      "Indications:",
      "• Intractable pain",
      "• Obstruction with infection",
      "• Bilateral obstruction",
      "• Solitary kidney",
      "• AKI",
      "",
      "Options:",
      "• Ureteral stent placement (most common)",
      "• Percutaneous nephrostomy",
      "• Ureteroscopy with stone extraction",
      "• ESWL contraindicated in pregnancy"
    ]
  },
  {
    title: "Medications and the Kidney in Pregnancy",
    subtitle: "Nephrotoxins to Avoid",
    content: [
      "Absolutely Contraindicated:",
      "• ACE inhibitors (captopril, enalapril, lisinopril)",
      "  - Renal dysgenesis, oligohydramnios, IUGR, fetal death",
      "• ARBs (losartan, valsartan)",
      "  - Same as ACE inhibitors",
      "• Direct renin inhibitors (aliskiren)",
      "",
      "NSAIDs:",
      "• Avoid in first trimester (risk of miscarriage)",
      "• Avoid after 20 weeks (oligohydramnios, renal dysfunction)",
      "• May close ductus arteriosus",
      "• Short course for tocolysis acceptable (<32 weeks)",
      "",
      "Aminoglycosides:",
      "• Gentamicin, tobramycin",
      "• Risk of fetal ototoxicity and nephrotoxicity",
      "• Use only if essential (endocarditis, pyelonephritis)",
      "• Single daily dosing, monitor levels",
      "",
      "Other Considerations:",
      "• Lithium: avoid if possible (Ebstein anomaly, neonatal toxicity)",
      "• Tetracyclines: avoid (dental staining, hepatotoxicity)",
      "• Trimethoprim: avoid first trimester (folate antagonist)",
      "• Nitrofurantoin: avoid at term (neonatal hemolysis)"
    ]
  },
  {
    title: "Safe Medications in Pregnancy",
    subtitle: "Renal Disease Management",
    content: [
      "Antihypertensives:",
      "• Methyldopa (first-line)",
      "• Labetalol",
      "• Nifedipine (long-acting)",
      "• Hydralazine (adjunct)",
      "",
      "Antibiotics (for UTI/pyelonephritis):",
      "• Penicillins (amoxicillin, ampicillin)",
      "• Cephalosporins (cephalexin, cefazolin, ceftriaxone)",
      "• Nitrofurantoin (avoid at term)",
      "• Fosfomycin",
      "",
      "Immunosuppression:",
      "• Prednisone",
      "• Azathioprine",
      "• Tacrolimus",
      "• Cyclosporine",
      "• AVOID: mycophenolate, sirolimus, methotrexate",
      "",
      "Diuretics:",
      "• Generally avoid (reduce placental perfusion)",
      "• Furosemide acceptable if pulmonary edema",
      "• Thiazides associated with neonatal thrombocytopenia",
      "",
      "Other:",
      "• Erythropoietin (safe, effective)",
      "• Insulin (treatment of choice for diabetes)",
      "• Low-dose aspirin 81 mg (safe, beneficial for preeclampsia prevention)"
    ]
  },
  {
    title: "Postpartum Renal Considerations",
    subtitle: "Recovery and Follow-Up",
    content: [
      "Normal Postpartum Changes:",
      "• Physiologic hydronephrosis resolves 6-12 weeks",
      "• GFR returns to baseline 6-12 weeks",
      "• Proteinuria resolves if pregnancy-related",
      "• Blood pressure normalizes 12 weeks if gestational HTN",
      "",
      "Postpartum Evaluation:",
      "• Blood pressure monitoring (preeclampsia risk continues 6 weeks)",
      "• Urinalysis at 3 months",
      "• Serum creatinine at 3 months",
      "• If proteinuria or elevated Cr persists: evaluate for CKD",
      "",
      "Preeclampsia Postpartum:",
      "• 30% of eclampsia occurs postpartum",
      "• Monitor BP for 72 hours after delivery",
      "• Weekly BP checks for 6 weeks",
      "• Continue antihypertensives as needed",
      "• May need magnesium sulfate postpartum",
      "",
      "Breastfeeding Considerations:",
      "• Most antihypertensives safe",
      "• Immunosuppressants (azathioprine, tacrolimus) usually acceptable",
      "• Check drug compatibility (LactMed database)",
      "• Benefits of breastfeeding usually outweigh minimal risks"
    ]
  },
  {
    title: "Future Pregnancy Planning",
    subtitle: "Preconception Counseling",
    content: [
      "Timing of Next Pregnancy:",
      "• Wait 18-24 months after preeclampsia",
      "• Wait 12-18 months for renal recovery if AKI",
      "• CKD: ensure stability 6 months",
      "• Transplant: wait 1-2 years",
      "",
      "Risk Assessment:",
      "• Previous preeclampsia: 15-25% recurrence",
      "• History of HELLP: 3-5% recurrence",
      "• CKD: counsel based on stage and etiology",
      "• Review maternal and fetal risks",
      "",
      "Optimization:",
      "• Achieve healthy weight",
      "• Optimal BP control (<140/90)",
      "• Switch to pregnancy-safe medications",
      "• Folic acid 400-800 μg daily",
      "• Control diabetes (HbA1c <6.5%)",
      "",
      "Preventive Measures:",
      "• Low-dose aspirin 81-162 mg from 12 weeks if high risk",
      "  - Previous preeclampsia",
      "  - Multifetal gestation",
      "  - CKD, chronic HTN, diabetes, autoimmune disease",
      "• Calcium supplementation if low dietary intake"
    ]
  },
  {
    title: "Key Clinical Pearls",
    subtitle: "Important Takeaways",
    content: [
      "1. Normal pregnancy GFR increases 40-50%; Cr >0.9 mg/dL is abnormal",
      "",
      "2. Proteinuria up to 300 mg/24h is physiologic in pregnancy",
      "",
      "3. Physiologic hydronephrosis is normal; more on right than left",
      "",
      "4. Screen all pregnant women for asymptomatic bacteriuria at first visit",
      "",
      "5. Pyelonephritis requires hospitalization and IV antibiotics",
      "",
      "6. Preeclampsia is diagnosed after 20 weeks by BP + proteinuria or end-organ damage",
      "",
      "7. Glomerular endotheliosis is pathognomonic for preeclampsia",
      "",
      "8. Delivery is the only cure for preeclampsia; timing depends on severity and gestational age",
      "",
      "9. Magnesium sulfate prevents eclamptic seizures in severe preeclampsia",
      "",
      "10. HELLP syndrome: hemolysis, elevated liver enzymes, low platelets - deliver promptly",
      "",
      "11. ACE inhibitors and ARBs are teratogenic and absolutely contraindicated",
      "",
      "12. CKD pregnancy outcomes correlate with baseline GFR and proteinuria"
    ]
  },
  {
    title: "Key Clinical Pearls (Continued)",
    subtitle: "Important Takeaways",
    content: [
      "13. Lupus nephritis: pregnancy safest when disease quiescent 6-12 months",
      "",
      "14. Mycophenolate and sirolimus must be stopped before conception",
      "",
      "15. Hydroxychloroquine should be continued throughout pregnancy in lupus",
      "",
      "16. Kidney transplant patients should wait 1-2 years post-transplant",
      "",
      "17. Pregnancy on dialysis: intensive dialysis (≥20 hours/week) improves outcomes",
      "",
      "18. Target predialysis BUN <50 mg/dL in pregnant dialysis patients",
      "",
      "19. Acute fatty liver of pregnancy requires immediate delivery",
      "",
      "20. Atypical HUS typically presents postpartum; treat with eculizumab",
      "",
      "21. Cortical necrosis often follows placental abruption; prognosis poor",
      "",
      "22. Most kidney stones in pregnancy pass spontaneously with conservative management",
      "",
      "23. Postpartum follow-up essential: BP, urinalysis, creatinine at 3 months",
      "",
      "24. Low-dose aspirin reduces preeclampsia risk in high-risk women (start 12 weeks)"
    ]
  },
  {
    title: "Summary",
    subtitle: "Pregnancy and Kidney - Overview",
    content: [
      "Pregnancy induces profound renal changes:",
      "• Anatomical: kidney enlargement, collecting system dilation",
      "• Hemodynamic: increased RBF and GFR by 40-50%",
      "• Biochemical: lower Cr, BUN, uric acid; mild proteinuria normal",
      "",
      "Major renal complications in pregnancy:",
      "• UTI/pyelonephritis: screen and treat aggressively",
      "• Preeclampsia: leading cause of maternal morbidity",
      "• AKI: multiple causes, requires rapid diagnosis and treatment",
      "",
      "Chronic kidney disease in pregnancy:",
      "• Outcomes depend on baseline function",
      "• Requires specialized multidisciplinary care",
      "• Increased risks of preeclampsia, preterm birth, IUGR",
      "",
      "Management principles:",
      "• Preconception optimization crucial",
      "• Avoid teratogenic medications (ACEi, ARBs, mycophenolate)",
      "• Intensive monitoring throughout pregnancy",
      "• Early recognition and treatment of complications",
      "• Delivery timing individualized based on severity"
    ]
  },
  {
    title: "References",
    subtitle: "Key Medical Texts",
    content: [
      "1. Davidson's Principles and Practice of Medicine, 24th Edition",
      "   • Chapter on Kidney and Urinary Tract Disease",
      "   • Chapter on Pregnancy and Reproductive Health",
      "",
      "2. Kumar and Clark's Clinical Medicine, 10th Edition",
      "   • Chapter 12: Kidney and Urinary Tract Disease",
      "   • Chapter 16: Women's Health",
      "",
      "3. Harrison's Principles of Internal Medicine, 21st Edition",
      "   • Chapter 306: Glomerular Diseases",
      "   • Chapter 309: Chronic Kidney Disease",
      "   • Chapter 311: Hypertensive Vascular Disease in Pregnancy",
      "",
      "Additional Clinical Guidelines:",
      "• ACOG Practice Bulletins on Hypertension in Pregnancy",
      "• KDIGO Clinical Practice Guidelines",
      "• National Institute for Health and Care Excellence (NICE) Guidelines"
    ]
  }
];

export default function Home() {
  const [currentSlide, setCurrentSlide] = useState(0);

  const nextSlide = () => {
    setCurrentSlide((prev) => (prev + 1) % slides.length);
  };

  const prevSlide = () => {
    setCurrentSlide((prev) => (prev - 1 + slides.length) % slides.length);
  };

  const goToSlide = (index) => {
    setCurrentSlide(index);
  };

  return (
    <div style={{
      width: '100vw',
      height: '100vh',
      display: 'flex',
      flexDirection: 'column',
      backgroundColor: '#1a1a2e',
      color: '#fff',
      overflow: 'hidden'
    }}>
      {/* Main Slide Area */}
      <div style={{
        flex: 1,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        padding: '40px',
        position: 'relative'
      }}>
        <div style={{
          maxWidth: '1200px',
          width: '100%',
          height: '100%',
          backgroundColor: '#16213e',
          borderRadius: '20px',
          padding: '60px',
          boxShadow: '0 10px 40px rgba(0,0,0,0.3)',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'auto'
        }}>
          <h1 style={{
            fontSize: currentSlide === 0 ? '3.5rem' : '2.5rem',
            marginBottom: '20px',
            color: '#0f4c75',
            borderBottom: '3px solid #0f4c75',
            paddingBottom: '15px'
          }}>
            {slides[currentSlide].title}
          </h1>

          {slides[currentSlide].subtitle && (
            <h2 style={{
              fontSize: '1.8rem',
              marginBottom: '30px',
              color: '#3282b8',
              fontWeight: 'normal'
            }}>
              {slides[currentSlide].subtitle}
            </h2>
          )}

          <div style={{
            fontSize: '1.3rem',
            lineHeight: '1.8',
            flex: 1,
            overflow: 'auto'
          }}>
            {slides[currentSlide].content.map((line, index) => (
              <p key={index} style={{
                margin: line === '' ? '15px 0' : '5px 0',
                paddingLeft: line.startsWith('•') ? '20px' : '0',
                fontWeight: line.endsWith(':') ? 'bold' : 'normal',
                color: line.startsWith('•') ? '#bbe1fa' : '#fff'
              }}>
                {line}
              </p>
            ))}
          </div>
        </div>

        {/* Navigation Arrows */}
        <button
          onClick={prevSlide}
          style={{
            position: 'absolute',
            left: '20px',
            top: '50%',
            transform: 'translateY(-50%)',
            fontSize: '3rem',
            background: '#0f4c75',
            border: 'none',
            color: '#fff',
            cursor: 'pointer',
            borderRadius: '50%',
            width: '60px',
            height: '60px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            transition: 'all 0.3s'
          }}
          onMouseOver={(e) => e.target.style.backgroundColor = '#3282b8'}
          onMouseOut={(e) => e.target.style.backgroundColor = '#0f4c75'}
        >
          ←
        </button>

        <button
          onClick={nextSlide}
          style={{
            position: 'absolute',
            right: '20px',
            top: '50%',
            transform: 'translateY(-50%)',
            fontSize: '3rem',
            background: '#0f4c75',
            border: 'none',
            color: '#fff',
            cursor: 'pointer',
            borderRadius: '50%',
            width: '60px',
            height: '60px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            transition: 'all 0.3s'
          }}
          onMouseOver={(e) => e.target.style.backgroundColor = '#3282b8'}
          onMouseOut={(e) => e.target.style.backgroundColor = '#0f4c75'}
        >
          →
        </button>
      </div>

      {/* Bottom Control Bar */}
      <div style={{
        padding: '20px',
        backgroundColor: '#0f0f1e',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderTop: '2px solid #0f4c75'
      }}>
        <div style={{ fontSize: '1.2rem', color: '#bbe1fa' }}>
          Slide {currentSlide + 1} of {slides.length}
        </div>

        <div style={{
          display: 'flex',
          gap: '10px',
          flexWrap: 'wrap',
          maxWidth: '70%',
          justifyContent: 'center'
        }}>
          {slides.map((_, index) => (
            <button
              key={index}
              onClick={() => goToSlide(index)}
              style={{
                width: '12px',
                height: '12px',
                borderRadius: '50%',
                border: 'none',
                backgroundColor: currentSlide === index ? '#0f4c75' : '#3a3a4a',
                cursor: 'pointer',
                transition: 'all 0.3s'
              }}
              onMouseOver={(e) => {
                if (currentSlide !== index) e.target.style.backgroundColor = '#5a5a6a';
              }}
              onMouseOut={(e) => {
                if (currentSlide !== index) e.target.style.backgroundColor = '#3a3a4a';
              }}
            />
          ))}
        </div>

        <div style={{ width: '100px' }}></div>
      </div>
    </div>
  );
}
